Repository VICKY2501/Anddev, pull requests merged in 2021-10, with the labels that each got.

#1 Add files via upload
  Python/VendingMACHINE.py
Labels: hacktoberfest, good-first-contribution, kind/enhancement

#3 hackerrank
  hackerrank/conditionals_and_loops.cpp/Start_pattern.cpp
  hackerrank/conditionals_and_loops.cpp/Start_pattern.exe
  hackerrank/conditionals_and_loops.cpp/check_case.cpp
  hackerrank/conditionals_and_loops.cpp/check_case.exe
  hackerrank/conditionals_and_loops.cpp/fahrenheit_to_celcius.cpp
  hackerrank/conditionals_and_loops.cpp/fahrenheit_to_celcius.exe
  hackerrank/conditionals_and_loops.cpp/find_power_ofa_no.cpp
  hackerrank/conditionals_and_loops.cpp/find_power_ofa_no.exe
  hackerrank/conditionals_and_loops.cpp/no_pattern1.cpp
  hackerrank/conditionals_and_loops.cpp/no_pattern1.exe
  hackerrank/conditionals_and_loops.cpp/no_pattern2.cpp
  hackerrank/conditionals_and_loops.cpp/no_pattern2.exe
  hackerrank/conditionals_and_loops.cpp/sum_of_even_nos_till_N.cpp
  hackerrank/conditionals_and_loops.cpp/sum_of_even_nos_till_N.exe
  hackerrank/conditionals_and_loops.cpp/sumofevenandodd.cpp
  hackerrank/conditionals_and_loops.cpp/sumofevenandodd.exe
  hackerrank/conditionals_and_loops.cpp/totalsalary.cpp
  hackerrank/conditionals_and_loops.cpp/totalsalary.exe
Labels: hacktoberfest, good-first-contribution, good-first-issue

#2 Add files via upload
  Python/HEALTHYPROGRSMMER.py
  Python/filewritingatext.py
  Python/fstring.py
Labels: good first issue, hacktoberfest, good-first-contribution

#6 Add files via upload
  Python/knapsack.py
Labels: hacktoberfest, good-first-contribution, good-first-issue
